version: "3.1"
services:
    postgres:
      image: postgres:latest
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: 12345678
        POSTGRES_USER: user1
        POSTGRES_DB: webserver
      ports:
        - 5432:5432

